apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: simple-fastapi-virtual-server
spec:
  host: localhost
  policies:
  - name: simple-fastapi-key-policy-1
  - name: simple-fastapi-key-policy-2
  - name: simple-fastapi-key-policy-3
  upstreams:
  - name: simple-fastapi-service
    service: simple-fastapi-service
    port: 80
  routes:
  - path: /
    action:
      pass: simple-fastapi-service
