apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-fastapi-app
  labels:
    app: simple-fastapi-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-fastapi-app
  template:
    metadata:
      labels:
        app: simple-fastapi-app
    spec:
      containers:
      - name: simple-fastapi-app
        image: skongbitdefender/simple-fastapi-app
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: simple-fastapi-service
spec:
  selector:
    app: simple-fastapi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
